# Generated by Django 3.2.4 on 2022-09-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15)),
                ('gerente', models.CharField(max_length=50)),
                ('profesional', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('dirreccion', models.CharField(max_length=50)),
                ('visitaprimaria', models.DateTimeField()),
                ('visitasecundaria', models.DateTimeField()),
                ('capacitacion', models.CharField(max_length=120)),
                ('capacitacionfecha', models.DateTimeField()),
                ('asesoria', models.DateTimeField()),
                ('asesoriafecha', models.DateTimeField()),
                ('actividadmejora', models.CharField(max_length=120)),
                ('accidentabilidad', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
